export type AuditEventType =
  | "AUTH_SUCCESS"
  | "SESSION_CREATED"
  | "SESSION_REVOKED"
  | "PERSONAL_ACCOUNT_LOOKUP"
  | "PROPERTY_RESOLVED"
  | "ELIGIBILITY_RESOLVED"
  | "SURVEY_OPENED"
  | "VOTE_STARTED"
  | "VOTE_RESUMED"
  | "VOTE_ANSWER_CHANGED"
  | "VOTE_SUBMIT_ATTEMPT"
  | "VOTE_SUBMITTED"
  | "signature_started"
  | "signature_completed"
  | "document_generated"
  | "admin_change";
