"use client";

/* eslint-disable @next/next/no-html-link-for-pages -- Admin rows use native anchors for explicit, bookmarkable routes. */

import {
  Activity, Archive, ArrowDown, ArrowLeft, ArrowUp, BarChart3, Building2, CheckCircle2, ChevronLeft, ChevronRight,
  ClipboardList, Copy, Download, Eye, FileCheck2, FileText, Gauge, LayoutDashboard, LockKeyhole, LogOut, Menu,
  Pencil, Plus, Search, Settings, ShieldCheck, Trash2, Upload, UserRoundCog, Users, X,
} from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useState, type FormEvent, type ReactNode } from "react";
import type { AdminPrincipal } from "@/src/domain/admin-rbac";

type Json = Record<string, unknown>;
type PageData = { items: Json[]; total: number; page: number; pageSize: number };
type Survey = Json & { id: string; titleRu: string; titleKk?: string; protocolNumber: string; status: string; version: number; lockVersion: number; startsAt: string; closesAt: string; descriptionRu?: string; descriptionKk?: string; questions?: Question[]; targets?: Json[]; questionCount?: number; eligibleCount?: number; completedCount?: number };
type Question = { id: string; position: number; textRu: string; textKk: string; required: boolean };

const navigation = [
  ["", "Обзор", LayoutDashboard], ["surveys", "Опросы", ClipboardList], ["documents", "Документы", FileCheck2],
  ["audit", "Аудит", Activity], ["users", "Доступы", UserRoundCog], ["settings", "Настройки", Settings],
] as const;
const statusNames: Record<string,string>={draft:"Черновик",scheduled:"Запланирован",active:"Активен",closed:"Закрыт",archived:"Архив"};

async function api<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(`/api/admin${path}`,{cache:"no-store",...init,headers:{...(init?.body?{"content-type":"application/json"}:{}),...init?.headers}});if(!response.ok){const body=await response.json().catch(()=>null) as {error?:{message?:string;code?:string}}|null;throw new Error(body?.error?.message||body?.error?.code||`HTTP ${response.status}`);}if(response.status===204)return undefined as T;return response.json() as Promise<T>;}
const formatDate=(value:unknown)=>value?new Intl.DateTimeFormat("ru-RU",{dateStyle:"medium",timeStyle:"short"}).format(new Date(String(value))):"—";
const percent=(value:unknown)=>`${Number(value||0).toLocaleString("ru-RU",{maximumFractionDigits:2})}%`;

export function AdminConsole({initialPath,principal}:{initialPath:string[];principal:AdminPrincipal}){
  const router=useRouter();
  const [mobileNav,setMobileNav]=useState(false);const [toast,setToast]=useState("");
  const section=initialPath[0]??"";const title=section==="surveys"?"Опросы":section==="documents"?"Документы":section==="audit"?"Журнал аудита":section==="users"?"Пользователи и роли":section==="settings"?"Настройки":"Обзор";
  async function logout(){await fetch("/api/session",{method:"DELETE"});router.push("/admin/login");router.refresh();}
  useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(""),3200);return()=>clearTimeout(id);},[toast]);
  return <div className="admin-app"><aside className={`admin-sidebar ${mobileNav?"open":""}`}><div className="admin-brand"><span><Building2 size={22}/></span><div><strong>Астана-ЕРЦ</strong><small>ОПРОСЫ · ADMIN</small></div><button onClick={()=>setMobileNav(false)} aria-label="Закрыть меню"><X size={20}/></button></div><nav>{navigation.map(([path,label,Icon])=><Link className={section===path?"active":""} href={`/admin${path?`/${path}`:""}`} key={path}><Icon size={18}/>{label}</Link>)}</nav><div className="admin-sidebar-foot"><ShieldCheck size={17}/><span><strong>{principal.displayName}</strong><small>{principal.roles.join(", ")}</small></span></div></aside>
    <div className="admin-main"><header className="admin-header"><button className="admin-menu" onClick={()=>setMobileNav(true)} aria-label="Открыть меню"><Menu/></button><div><small>Администрирование / {title}</small><h1>{title}</h1></div><div className="admin-user"><span>{principal.displayName.slice(0,2).toUpperCase()}</span><button onClick={logout} title="Выйти"><LogOut size={18}/></button></div></header><main className="admin-content"><RouteView path={initialPath} principal={principal} notify={setToast}/></main></div>{toast?<div className="admin-toast"><CheckCircle2 size={18}/>{toast}</div>:null}</div>;
}

function RouteView({path,principal,notify}:{path:string[];principal:AdminPrincipal;notify:(value:string)=>void}){
  if(!path.length)return <Dashboard/>;
  if(path[0]==="surveys"){
    if(path[1]==="new")return <SurveyEditor notify={notify}/>;
    if(path[1]&&path[2]==="edit")return <SurveyEditor id={path[1]} notify={notify}/>;
    if(path[1]&&path[2]==="results")return <Results id={path[1]}/>;
    if(path[1]&&path[2]==="participants")return <Participants id={path[1]}/>;
    if(path[1])return <SurveyDetail id={path[1]} notify={notify}/>;
    return <SurveyList/>;
  }
  if(path[0]==="documents")return path[1]?<DocumentDetail id={path[1]} principal={principal}/>:<Documents/>;
  if(path[0]==="audit")return <Audit/>;
  if(path[0]==="users")return <AdminUsers notify={notify}/>;
  if(path[0]==="settings")return <SettingsPage principal={principal}/>;
  return <Empty title="Раздел не найден"/>;
}

function useLoad<T>(loader:()=>Promise<T>,deps:readonly unknown[]){const [data,setData]=useState<T>();const [error,setError]=useState("");const [loading,setLoading]=useState(true);
  // This utility deliberately exposes caller-owned primitive dependencies, equivalent to a query key.
  // eslint-disable-next-line react-hooks/use-memo, react-hooks/exhaustive-deps
  const load=useCallback(()=>{setLoading(true);setError("");return loader().then(setData).catch((e:Error)=>setError(e.message)).finally(()=>setLoading(false));},deps);
  useEffect(()=>{void load();},[load]);return{data,error,loading,reload:load};}
function Loading(){return <div className="admin-skeleton"><span/><span/><span/><span/></div>}
function ErrorBox({message}:{message:string}){return <div className="admin-alert danger">{message}</div>}
function Empty({title,copy="Данных по выбранным условиям пока нет."}:{title:string;copy?:string}){return <div className="admin-empty"><FileText size={32}/><h3>{title}</h3><p>{copy}</p></div>}
function Badge({status}:{status:string}){return <span className={`admin-badge ${status}`}>{statusNames[status]??status}</span>}

function Dashboard(){const state=useLoad(()=>api<Json>("/dashboard"),[]);if(state.loading)return <Loading/>;if(state.error)return <ErrorBox message={state.error}/>;const d=state.data??{};const surveys=(d.surveys??{}) as Json;const participants=(d.participants??{})as Json;const documents=(d.documents??{})as Json;const activity=(d.activity??[])as Json[];return <><section className="admin-hero"><div><span className="admin-kicker">CONTROL CENTER</span><h2>Состояние платформы</h2><p>Только фактические данные PostgreSQL на текущий момент.</p></div><Gauge size={42}/></section><div className="admin-metric-grid"><Metric label="Активные опросы" value={surveys.active}/><Metric label="Запланировано" value={surveys.scheduled}/><Metric label="Черновики" value={surveys.draft}/><Metric label="Закрыто" value={surveys.closed}/><Metric label="Eligible" value={participants.eligible}/><Metric label="Started" value={participants.started}/><Metric label="Completed" value={participants.completed}/><Metric label="Участие" value={percent(d.participationPercent)}/><Metric label="Финальные документы" value={documents.finalized}/></div><Panel title="Последняя активность" action={<a href="/admin/audit">Весь журнал</a>}><DataTable headers={["Событие","Исполнитель","Результат","Дата"]}>{activity.map(row=><tr key={String(row.id)}><td><strong>{String(row.eventType)}</strong></td><td>{String(row.actor??"Система")}</td><td><span className="admin-dot success"/> {String(row.outcome)}</td><td>{formatDate(row.occurredAt)}</td></tr>)}</DataTable></Panel></>}
function Metric({label,value}:{label:string;value:unknown}){return <article className="admin-metric"><small>{label}</small><strong>{String(value??0)}</strong><span>Актуально сейчас</span></article>}

function SurveyList(){const [search,setSearch]=useState("");const [status,setStatus]=useState("");const [from,setFrom]=useState("");const [to,setTo]=useState("");const [page,setPage]=useState(1);const url=`/surveys?page=${page}&pageSize=15&search=${encodeURIComponent(search)}&status=${status}&from=${from}&to=${to}`;const state=useLoad(()=>api<PageData>(url),[url]);return <><div className="admin-toolbar"><div className="admin-search"><Search size={17}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Название или протокол"/></div><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">Все статусы</option>{Object.entries(statusNames).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input aria-label="Период от" type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1)}}/><input aria-label="Период до" type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1)}}/><a className="admin-button primary" href="/admin/surveys/new"><Plus size={17}/>Новый опрос</a></div>{state.loading?<Loading/>:state.error?<ErrorBox message={state.error}/>:!state.data?.items.length?<Empty title="Опросы не найдены"/>:<Panel title={`Опросы · ${state.data.total}`}><DataTable headers={["Опрос","Протокол","Статус","Версия","Период","Вопросы","Eligible","Completed",""]}>{state.data.items.map(raw=>{const row=raw as Survey;return <tr key={row.id}><td><strong>{row.titleRu}</strong><small>{row.titleKk||"KZ не задан"}</small></td><td>№{row.protocolNumber}</td><td><Badge status={row.status}/></td><td>v{row.version}</td><td>{formatDate(row.startsAt)}<small>до {formatDate(row.closesAt)}</small></td><td>{row.questionCount}</td><td>{row.eligibleCount}</td><td>{row.completedCount}</td><td><a className="admin-icon-link" href={`/admin/surveys/${row.id}`} aria-label="Открыть"><ChevronRight size={18}/></a></td></tr>})}</DataTable><Pagination current={page} total={state.data.total} size={state.data.pageSize} onChange={setPage}/></Panel>}</>}

function SurveyEditor({id,notify}:{id?:string;notify:(value:string)=>void}){const router=useRouter();const state=useLoad(()=>id?api<Survey>(`/surveys/${id}`):Promise.resolve(undefined as unknown as Survey),[id]);const survey=state.data;const [form,setForm]=useState({protocolNumber:"",titleRu:"",titleKk:"",descriptionRu:"",descriptionKk:"",startsAt:"",closesAt:""});const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  // Loaded server data is the authoritative reset point for this controlled draft form.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{if(!survey)return;setForm({protocolNumber:survey.protocolNumber,titleRu:survey.titleRu,titleKk:survey.titleKk??"",descriptionRu:survey.descriptionRu??"",descriptionKk:survey.descriptionKk??"",startsAt:toLocal(survey.startsAt),closesAt:toLocal(survey.closesAt)});},[survey]);
  async function save(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{const body={...form,startsAt:new Date(form.startsAt).toISOString(),closesAt:new Date(form.closesAt).toISOString(),...(survey?{expectedLockVersion:survey.lockVersion}:{})};const result=await api<Survey>(survey?`/surveys/${survey.id}`:"/surveys",{method:survey?"PATCH":"POST",body:JSON.stringify(body)});notify(survey?"Черновик сохранён":"Опрос создан");if(!survey){router.push(`/admin/surveys/${result.id}/edit`);router.refresh();}else await state.reload();}catch(e){setError((e as Error).message.includes("lock version")?"Опрос был изменён другим пользователем. Обновите страницу перед сохранением.":(e as Error).message);}finally{setBusy(false)}}
  if(id&&state.loading)return <Loading/>;if(state.error)return <ErrorBox message={state.error}/>;if(survey&&survey.status!=="draft")return <ErrorBox message="Опубликованный опрос нельзя свободно редактировать."/>;
  return <><Back href={id?`/admin/surveys/${id}`:"/admin/surveys"}/><div className="admin-builder"><section><form className="admin-form-card" onSubmit={save}><div className="admin-section-title"><div><span className="admin-kicker">ШАГ 1</span><h2>Основные сведения</h2></div><Badge status="draft"/></div>{error?<ErrorBox message={error}/>:null}<div className="admin-form-grid"><Field label="Номер протокола"><input required maxLength={120} value={form.protocolNumber} onChange={e=>setForm({...form,protocolNumber:e.target.value})}/></Field><Field label="Начало"><input required type="datetime-local" value={form.startsAt} onChange={e=>setForm({...form,startsAt:e.target.value})}/></Field><Field label="Завершение"><input required type="datetime-local" value={form.closesAt} onChange={e=>setForm({...form,closesAt:e.target.value})}/></Field><Field label="Название · RU"><input required value={form.titleRu} onChange={e=>setForm({...form,titleRu:e.target.value})}/></Field><Field label="Название · KZ"><input required value={form.titleKk} onChange={e=>setForm({...form,titleKk:e.target.value})}/></Field><Field label="Описание · RU"><textarea required value={form.descriptionRu} onChange={e=>setForm({...form,descriptionRu:e.target.value})}/></Field><Field label="Описание · KZ"><textarea required value={form.descriptionKk} onChange={e=>setForm({...form,descriptionKk:e.target.value})}/></Field></div><button className="admin-button primary" disabled={busy}>{busy?"Сохраняем…":"Сохранить черновик"}</button></form>{survey?<><QuestionBuilder survey={survey} reload={state.reload} notify={notify}/><TargetBuilder survey={survey} reload={state.reload} notify={notify}/></>:null}</section><PhonePreview survey={survey} form={form}/></div></>}

function QuestionBuilder({survey,reload,notify}:{survey:Survey;reload:()=>Promise<void>;notify:(v:string)=>void}){const [draft,setDraft]=useState({textRu:"",textKk:"",required:true});const [error,setError]=useState("");async function add(){try{await api(`/surveys/${survey.id}/questions`,{method:"POST",body:JSON.stringify(draft)});setDraft({textRu:"",textKk:"",required:true});notify("Вопрос добавлен");await reload();}catch(e){setError((e as Error).message)}}async function action(question:Question,kind:"up"|"down"|"duplicate"|"delete"){try{const path=`/surveys/${survey.id}/questions/${question.id}`;if(kind==="delete")await api(path,{method:"DELETE"});else await api(`${path}/${kind==="duplicate"?"duplicate":"move"}`,{method:"POST",body:kind==="duplicate"?undefined:JSON.stringify({direction:kind})});notify("Порядок вопросов обновлён");await reload();}catch(e){setError((e as Error).message)}}return <section className="admin-form-card"><div className="admin-section-title"><div><span className="admin-kicker">ШАГ 2</span><h2>Вопросы · {survey.questions?.length??0}</h2></div></div>{error?<ErrorBox message={error}/>:null}<div className="admin-question-list">{survey.questions?.map(q=><article key={q.id}><span>{q.position}</span><div><strong>{q.textRu}</strong><small>{q.textKk}</small><em>{q.required?"Обязательный":"Необязательный"} · FOR / AGAINST / ABSTAIN</em></div><div><button onClick={()=>action(q,"up")} aria-label="Выше"><ArrowUp size={16}/></button><button onClick={()=>action(q,"down")} aria-label="Ниже"><ArrowDown size={16}/></button><button onClick={()=>action(q,"duplicate")} aria-label="Дублировать"><Copy size={16}/></button><button onClick={()=>action(q,"delete")} aria-label="Удалить"><Trash2 size={16}/></button></div></article>)}</div><div className="admin-inline-form"><input placeholder="Текст вопроса RU" value={draft.textRu} onChange={e=>setDraft({...draft,textRu:e.target.value})}/><input placeholder="Сұрақ мәтіні KZ" value={draft.textKk} onChange={e=>setDraft({...draft,textKk:e.target.value})}/><label><input type="checkbox" checked={draft.required} onChange={e=>setDraft({...draft,required:e.target.checked})}/> Обязательный</label><button className="admin-button secondary" disabled={!draft.textRu||!draft.textKk} onClick={add}><Plus size={16}/>Добавить</button></div></section>}

function TargetBuilder({survey,reload,notify}:{survey:Survey;reload:()=>Promise<void>;notify:(v:string)=>void}){
  const references=useLoad(()=>api<{organizations:Json[];properties:Json[];accounts:Json[]}>("/references"),[]);
  const [building,setBuilding]=useState({city:"Астана",street:"Геодезическая",building:"12"});const [propertyIds,setPropertyIds]=useState<string[]>([]);const [organizationId,setOrganizationId]=useState("");
  const [csv,setCsv]=useState("");const [preview,setPreview]=useState<Json>();const [error,setError]=useState("");
  async function save(targets:Json[]){try{await api(`/surveys/${survey.id}/targets`,{method:"PUT",body:JSON.stringify({targets})});notify("Аудитория сохранена");await reload();}catch(e){setError((e as Error).message)}}
  async function previewCsv(){try{setPreview(await api("/imports/accounts/preview",{method:"POST",body:JSON.stringify({csv})}));}catch(e){setError((e as Error).message)}}
  async function confirmCsv(){const items=(preview?.items??[])as {id:string}[];if(items.length)await save(items.map(item=>({type:"personal_account",personalAccountId:item.id})));}
  return <section className="admin-form-card"><div className="admin-section-title"><div><span className="admin-kicker">ШАГ 3</span><h2>Аудитория</h2></div><span>{survey.targets?.length??0} targets</span></div>{error?<ErrorBox message={error}/>:null}<div className="admin-target-grid">
    <div><h3><Building2 size={18}/>Дом</h3><Field label="Город"><input value={building.city} onChange={e=>setBuilding({...building,city:e.target.value})}/></Field><Field label="Улица"><input value={building.street} onChange={e=>setBuilding({...building,street:e.target.value})}/></Field><Field label="Дом"><input value={building.building} onChange={e=>setBuilding({...building,building:e.target.value})}/></Field><button className="admin-button secondary" onClick={()=>save([{type:"building",...building}])}>Назначить дому</button></div>
    <div><h3><Building2 size={18}/>Объекты</h3><Field label="Несколько помещений"><select multiple value={propertyIds} onChange={e=>setPropertyIds([...e.currentTarget.selectedOptions].map(option=>option.value))}>{references.data?.properties.map(property=><option key={String(property.id)} value={String(property.id)}>{property.city as string}, {property.street as string} {property.building as string}, {property.premise as string}</option>)}</select></Field><button className="admin-button secondary" disabled={!propertyIds.length} onClick={()=>save(propertyIds.map(propertyId=>({type:"property",propertyId})))}>Назначить объекты</button></div>
    <div><h3><Users size={18}/>Организация</h3><Field label="Организация"><select value={organizationId} onChange={e=>setOrganizationId(e.target.value)}><option value="">Выберите…</option>{references.data?.organizations.map(org=><option key={String(org.id)} value={String(org.id)}>{String(org.name)}</option>)}</select></Field><button className="admin-button secondary" disabled={!organizationId} onClick={()=>save([{type:"organization",organizationId}])}>Назначить организацию</button></div>
    <div><h3><Upload size={18}/>CSV лицевых счетов</h3><textarea value={csv} onChange={e=>setCsv(e.target.value)} placeholder={'account_number\n1911'}/><button className="admin-button secondary" onClick={previewCsv}>Проверить CSV</button>{preview?<div className="admin-import-summary"><span>Строк: {String(preview.total)}</span><span>Resolved: {String(preview.resolved)}</span><span>Duplicate: {String(preview.duplicate)}</span><span>Unresolved: {String((preview.unresolved as unknown[])?.length??0)}</span><button className="admin-button primary" onClick={confirmCsv}>Подтвердить import</button></div>:null}</div>
  </div></section>}

function PhonePreview({survey,form}:{survey?:Survey;form:Json}){const questions=survey?.questions??[];return <aside className="admin-preview"><div className="admin-preview-head"><Eye size={17}/>Предпросмотр · RU / KZ</div><div className="admin-phone"><span>ПРОТОКОЛ №{String(form.protocolNumber||"—")}</span><h3>{String(form.titleRu||"Название опроса")}</h3><p>{String(form.descriptionRu||"Описание появится здесь")}</p><small>{questions.length} вопросов · FOR / AGAINST / ABSTAIN</small>{questions.slice(0,3).map(q=><article key={q.id}><b>{q.position}</b><div><strong>{q.textRu}</strong><small>{q.textKk}</small></div></article>)}</div></aside>}

function SurveyDetail({id,notify}:{id:string;notify:(v:string)=>void}){const state=useLoad(()=>api<Survey>(`/surveys/${id}`),[id]);const [busy,setBusy]=useState(false);async function transition(action:"publish"|"close"|"archive"){const warning=action==="publish"?"После публикации вопросы текущей версии нельзя будет свободно изменить. Продолжить?":`Подтвердить действие «${action}»?`;if(!confirm(warning))return;setBusy(true);try{await api(`/surveys/${id}/${action}`,{method:"POST"});notify("Статус опроса обновлён");await state.reload();}catch(e){notify((e as Error).message)}finally{setBusy(false)}}if(state.loading)return <Loading/>;if(state.error||!state.data)return <ErrorBox message={state.error||"Опрос не найден"}/>;const s=state.data;return <><Back href="/admin/surveys"/><section className="admin-detail-head"><div><Badge status={s.status}/><h2>{s.titleRu}</h2><p>{s.titleKk}</p></div><div className="admin-actions"><a className="admin-button secondary" href={`/admin/surveys/${id}/results`}><BarChart3 size={17}/>Результаты</a><a className="admin-button secondary" href={`/admin/surveys/${id}/participants`}><Users size={17}/>Участники</a>{s.status==="draft"?<><a className="admin-button secondary" href={`/admin/surveys/${id}/edit`}><Pencil size={17}/>Редактировать</a><button className="admin-button primary" disabled={busy} onClick={()=>transition("publish")}><Upload size={17}/>Опубликовать</button></>:null}{s.status==="active"?<button className="admin-button danger" onClick={()=>transition("close")}>Закрыть</button>:null}{s.status==="closed"?<button className="admin-button secondary" onClick={()=>transition("archive")}><Archive size={17}/>Архивировать</button>:null}</div></section><div className="admin-summary-grid"><Summary label="Протокол" value={`№${s.protocolNumber}`}/><Summary label="Версия" value={`v${s.version}`}/><Summary label="Период" value={`${formatDate(s.startsAt)} — ${formatDate(s.closesAt)}`}/><Summary label="Аудитория" value={`${s.eligibleCount} eligible`}/></div><Panel title={`Вопросы · ${s.questions?.length??0}`}><div className="admin-read-questions">{s.questions?.map(q=><article key={q.id}><span>{q.position}</span><div><strong>{q.textRu}</strong><small>{q.textKk}</small></div></article>)}</div></Panel></>}

function Results({id}:{id:string}){const state=useLoad(()=>api<Json>(`/surveys/${id}/results`),[id]);if(state.loading)return <Loading/>;if(state.error||!state.data)return <ErrorBox message={state.error||"Нет данных"}/>;const participation=state.data.participation as Json;const questions=state.data.questions as Json[];return <><Back href={`/admin/surveys/${id}`}/><div className="admin-metric-grid compact"><Metric label="Eligible" value={participation.eligible}/><Metric label="Started" value={participation.started}/><Metric label="Completed" value={participation.completed}/><Metric label="Participation" value={percent(participation.percent)}/></div><Panel title="Итоги по вопросам" action={<a className="admin-button secondary" href={`/api/admin/surveys/${id}/results/export`}><Download size={16}/>CSV</a>}><DataTable headers={["№","Вопрос","FOR","AGAINST","ABSTAIN","Всего"]}>{questions.map(q=><tr key={String(q.questionId)}><td>{String(q.position)}</td><td><strong>{String(q.textRu)}</strong><small>{String(q.textKk??"")}</small></td><td className="result-for">{String(q.for)}</td><td className="result-against">{String(q.against)}</td><td>{String(q.abstain)}</td><td>{String(q.total)}</td></tr>)}</DataTable></Panel></>}
function Participants({id}:{id:string}){const [page,setPage]=useState(1);const [search,setSearch]=useState("");const state=useLoad(()=>api<PageData>(`/surveys/${id}/participants?page=${page}&pageSize=20&search=${encodeURIComponent(search)}`),[id,page,search]);return <><Back href={`/admin/surveys/${id}`}/><div className="admin-toolbar"><div className="admin-search"><Search size={17}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Reference, объект или последние 4 цифры"/></div></div>{state.loading?<Loading/>:state.error?<ErrorBox message={state.error}/>:<Panel title={`Участники · ${state.data?.total??0}`} action={<a className="admin-button secondary" href={`/api/admin/surveys/${id}/participants/export`}><Download size={16}/>CSV</a>}><DataTable headers={["Reference","Объект","Счёт","Eligibility","Vote state","Started","Submitted","Document ID"]}>{state.data?.items.map(r=><tr key={String(r.participantReference)}><td className="mono">{String(r.participantReference).slice(0,8)}…</td><td>{String(r.property)}</td><td className="mono">{String(r.account)}</td><td>{String(r.eligibility)}</td><td><Badge status={String(r.voteState)}/></td><td>{formatDate(r.startedAt)}</td><td>{formatDate(r.submittedAt)}</td><td className="mono">{r.documentId?String(r.documentId).slice(0,8)+"…":"—"}</td></tr>)}</DataTable><Pagination current={page} total={state.data?.total??0} size={20} onChange={setPage}/></Panel>}</>}

function Documents(){const [search,setSearch]=useState("");const [status,setStatus]=useState("");const [page,setPage]=useState(1);const state=useLoad(()=>api<PageData>(`/documents?page=${page}&pageSize=20&search=${encodeURIComponent(search)}&status=${status}`),[page,search,status]);return <><div className="admin-toolbar"><div className="admin-search"><Search size={17}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Document ID, протокол, опрос"/></div><select aria-label="Статус подписи" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">Все статусы подписи</option>{["created","pending","verified","finalized","failed","expired","cancelled"].map(value=><option key={value}>{value}</option>)}</select></div>{state.loading?<Loading/>:state.error?<ErrorBox message={state.error}/>:<Panel title={`Реестр · ${state.data?.total??0}`}><DataTable headers={["Document ID","Опрос","Протокол","Версия","Создан","Provider","Signature","Integrity",""]}>{state.data?.items.map(r=><tr key={String(r.documentId)}><td className="mono">{String(r.documentId)}</td><td>{String(r.survey)}</td><td>№{String(r.protocol)}</td><td>v{String(r.version)}</td><td>{formatDate(r.createdAt)}</td><td>{String(r.signingProvider)}</td><td><Badge status={String(r.signingStatus)}/></td><td><span className="admin-dot success"/> {String(r.integrityStatus)}</td><td><a className="admin-icon-link" href={`/admin/documents/${String(r.documentId)}`}><ChevronRight size={18}/></a></td></tr>)}</DataTable><Pagination current={page} total={state.data?.total??0} size={20} onChange={setPage}/></Panel>}</>}
function DocumentDetail({id,principal}:{id:string;principal:AdminPrincipal}){const state=useLoad(()=>api<Json>(`/documents/${id}`),[id]);if(state.loading)return <Loading/>;if(state.error||!state.data)return <ErrorBox message={state.error||"Документ не найден"}/>;const d=state.data;return <><Back href="/admin/documents"/><section className="admin-detail-head"><div><span className="admin-kicker">IMMUTABLE DOCUMENT</span><h2 className="mono">{id}</h2><p>{String(d.survey)} · Протокол №{String(d.protocol)}</p></div>{principal.permissions.includes("document.pdf.read")?<a className="admin-button primary" href={`/api/documents/${id}/pdf`} target="_blank"><Download size={17}/>Открыть PDF</a>:null}</section><div className="admin-detail-card">{Object.entries(d).map(([key,value])=><div key={key}><small>{key}</small><strong className={key.toLowerCase().includes("sha")?"mono break":""}>{String(value??"—")}</strong></div>)}</div></>}
function Audit(){const [filters,setFilters]=useState({search:"",eventType:"",subjectType:"",subjectId:"",requestId:"",from:"",to:""});const [page,setPage]=useState(1);const params=new URLSearchParams({page:String(page),pageSize:"25",...filters});const url=`/audit?${params}`;const state=useLoad(()=>api<PageData>(url),[url]);function change(key:keyof typeof filters,value:string){setFilters(current=>({...current,[key]:value}));setPage(1)}return <><div className="admin-toolbar audit-filters"><div className="admin-search"><Search size={17}/><input value={filters.search} onChange={e=>change("search",e.target.value)} placeholder="Событие или actor"/></div><input value={filters.eventType} onChange={e=>change("eventType",e.target.value)} placeholder="Тип события"/><select aria-label="Тип subject" value={filters.subjectType} onChange={e=>change("subjectType",e.target.value)}><option value="">Все объекты</option><option value="survey">Опрос</option><option value="document">Документ</option><option value="user">Пользователь</option><option value="vote">Голос</option></select><input value={filters.subjectId} onChange={e=>change("subjectId",e.target.value)} placeholder="Survey / Document ID"/><input value={filters.requestId} onChange={e=>change("requestId",e.target.value)} placeholder="Request ID"/><input aria-label="Аудит от" type="date" value={filters.from} onChange={e=>change("from",e.target.value)}/><input aria-label="Аудит до" type="date" value={filters.to} onChange={e=>change("to",e.target.value)}/><span className="admin-readonly"><LockKeyhole size={15}/>Только чтение</span></div>{state.loading?<Loading/>:state.error?<ErrorBox message={state.error}/>:<Panel title={`События · ${state.data?.total??0}`}><DataTable headers={["Дата","Событие","Actor","Subject","Request ID","Outcome"]}>{state.data?.items.map(r=><tr key={String(r.id)}><td>{formatDate(r.occurredAt)}</td><td><strong>{String(r.eventType)}</strong></td><td>{String(r.actor??"Система")}</td><td>{String(r.subjectType??"—")}<small className="mono">{String(r.subjectId??"").slice(0,12)}</small></td><td className="mono">{String(r.requestId)}</td><td>{String(r.outcome)}</td></tr>)}</DataTable><Pagination current={page} total={state.data?.total??0} size={25} onChange={setPage}/></Panel>}</>}

function AdminUsers({notify}:{notify:(v:string)=>void}){const [page,setPage]=useState(1);const users=useLoad(()=>api<PageData>(`/users?page=${page}&pageSize=20`),[page]);const roles=useLoad(()=>api<{items:Json[]}>("/roles"),[]);async function assign(id:string,role:string){try{await api(`/users/${id}/roles`,{method:"POST",body:JSON.stringify({role})});notify("Роль назначена");await users.reload()}catch(e){notify((e as Error).message)}}async function revoke(id:string,role:string){try{await api(`/users/${id}/roles/${role}`,{method:"DELETE"});notify("Роль отозвана");await users.reload()}catch(e){notify((e as Error).message)}}async function toggle(id:string,disabled:boolean){try{await api(`/users/${id}/access`,{method:"POST",body:JSON.stringify({disabled})});notify("Административный доступ обновлён");await users.reload()}catch(e){notify((e as Error).message)}}if(users.loading||roles.loading)return <Loading/>;if(users.error||roles.error)return <ErrorBox message={users.error||roles.error}/>;return <Panel title={`Пользователи · ${users.data?.total??0}`}><DataTable headers={["Пользователь","Статус","Platform roles","Активность","Управление"]}>{users.data?.items.map(u=>{const current=(u.roles??[])as string[];return <tr key={String(u.id)}><td><strong>{String(u.displayName)}</strong><small className="mono">{String(u.id).slice(0,13)}…</small></td><td>{u.adminDisabledAt?<Badge status="disabled"/>:<Badge status={String(u.status)}/>}</td><td><div className="admin-role-list">{current.map(role=><button key={role} title="Отозвать роль" onClick={()=>revoke(String(u.id),role)}>{role}<X size={12}/></button>)}</div></td><td>{formatDate(u.lastActivity)}</td><td><select defaultValue="" onChange={e=>{if(e.target.value)void assign(String(u.id),e.target.value);e.target.value=""}}><option value="">Назначить роль…</option>{roles.data?.items.map(r=><option key={String(r.key)} value={String(r.key)}>{String(r.name)}</option>)}</select><button className="admin-button ghost" onClick={()=>toggle(String(u.id),!u.adminDisabledAt)}>{u.adminDisabledAt?"Включить":"Отключить"}</button></td></tr>})}</DataTable><Pagination current={page} total={users.data?.total??0} size={20} onChange={setPage}/></Panel>}
function SettingsPage({principal}:{principal:AdminPrincipal}){return <><section className="admin-hero"><div><span className="admin-kicker">SECURITY BOUNDARY</span><h2>Конфигурация Stage 4</h2><p>Provider settings управляются только environment variables. UI не содержит credentials и production bypass.</p></div><ShieldCheck size={42}/></section><Panel title="Ваши capabilities"><div className="admin-capabilities">{principal.permissions.map(p=><span key={p}>{p}</span>)}</div></Panel></>}

function Panel({title,action,children}:{title:string;action?:ReactNode;children:ReactNode}){return <section className="admin-panel"><header><h2>{title}</h2>{action}</header>{children}</section>}
function DataTable({headers,children}:{headers:string[];children:ReactNode}){return <div className="admin-table-wrap"><table className="admin-table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function Pagination({current,total,size,onChange}:{current:number;total:number;size:number;onChange:(p:number)=>void}){const pages=Math.max(1,Math.ceil(total/size));return <div className="admin-pagination"><span>Страница {current} из {pages} · {total} записей</span><div><button disabled={current<=1} onClick={()=>onChange(current-1)}><ChevronLeft/></button><button disabled={current>=pages} onClick={()=>onChange(current+1)}><ChevronRight/></button></div></div>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="admin-field"><span>{label}</span>{children}</label>}
function Back({href}:{href:string}){return <a className="admin-back" href={href}><ArrowLeft size={17}/>Назад</a>}
function Summary({label,value}:{label:string;value:string}){return <article><small>{label}</small><strong>{value}</strong></article>}
function toLocal(value:string){if(!value)return"";const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
